version: '3'
services:
  redmine-studio:
    image: haru/redmine-studio:1.1-${REDMINE_VER:-5.0.5}-${RUBY_VER:-3.0.0}
    build:
      context: build
      args:
        REDMINE_VER: ${REDMINE_VER:-5.0.5}
        RUBY_VER: ${RUBY_VER:-3.0.0}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - ./plugins:/home/workspace/redmine/plugins
      - ./db:/home/workspace/redmine/db/data
      - ./files:/home/workspace/redmine/files

