name: build
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ::set-output name=version::$VERSION
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build 
        if: success()
        run: |
          docker build -t ${{ github.repository }}:latest .
          docker tag ${{ github.repository }}:latest ${{ github.repository }}:${{ steps.version.outputs.version }}
      - name: Deploy :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ github.repository }}:latest
      - name: Deploy :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ github.repository }}:${{ steps.version.outputs.version }}

